name: Update AWS GeoIP SRS

on:
  schedule:
    # 06:00 по Москве = 03:00 UTC
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Install sing-box (official script)
        run: |
          curl -fsSL https://sing-box.app/install.sh | sh
          sudo mv /usr/local/bin/sing-box /usr/bin/sing-box || true
          sing-box version

      - name: Download AWS IPv4 ranges and build JSON
        run: |
          curl -s https://ip-ranges.amazonaws.com/ip-ranges.json -o aws_raw.json

          jq '{
            version: 1,
            rules: [
              {
                ip_cidr: [
                  .prefixes[].ip_prefix
                ]
              }
            ]
          }' aws_raw.json > geoip-aws.json

      - name: Compile SRS
        run: |
          sing-box rule-set compile -o geoip-aws.srs geoip-aws.json

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add geoip-aws.json geoip-aws.srs
          git commit -m "Auto-update AWS GeoIP SRS" || echo "No changes"
          git push
