name: Update Russia Rules Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Каждый день в 00:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Update all rules files with backup
        run: python update_script.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Добавляем все новые файлы
          git add geoip-ru-blocked.srs \
                 geoip-ru-blocked-community.srs \
                 geosite-ru-blocked-all.srs \
                 geosite-speedtest.srs \
                 geosite-twitch.srs \
                 geosite-discord.srs
          
          # Также добавляем папку old если там есть файлы
          if [ -d "old" ] && [ "$(ls -A old)" ]; then
            git add old/
          fi
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update all rules with backup $(date +'%Y-%m-%d %H:%M')"
            git push
          fi
